# Generated by Django 3.1.6 on 2021-03-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_comment',
            new_name='reply',
        ),
    ]
